-- 1. Kích hoạt các extension cần thiết
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. ENUMS (Định nghĩa các giá trị cố định)
CREATE TYPE subscription_tier AS ENUM ('BASIC', 'PRO', 'PREMIUM');
CREATE TYPE deploy_status AS ENUM ('draft', 'building', 'published', 'failed');

-- 3. TABLES (Bảng dữ liệu)

-- Kiem tra xem bang profiles da ton tai chua, neu chua thi tao
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  tier subscription_tier DEFAULT 'BASIC',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bảng TEMPLATES
CREATE TABLE IF NOT EXISTS templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  thumbnail_url TEXT,
  demo_url TEXT,
  repo_branch TEXT, -- Branch tuong ung tren git
  is_active BOOLEAN DEFAULT true,
  default_content JSONB DEFAULT '{}'::jsonb, -- Cấu hình mẫu cho theme này
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bảng WEDDINGS
CREATE TABLE IF NOT EXISTS weddings (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  host_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  template_id BIGINT REFERENCES templates(id),
  slug TEXT UNIQUE NOT NULL,
  
  content JSONB DEFAULT '{}'::jsonb, 
  
  google_sheet_id TEXT, 
  google_sheet_url TEXT,
  
  deployment_status deploy_status DEFAULT 'DRAFT',
  deployment_url TEXT,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bảng RSVPS
CREATE TABLE IF NOT EXISTS rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wedding_id UUID REFERENCES weddings(id) ON DELETE CASCADE NOT NULL,
  
  guest_name TEXT NOT NULL,
  phone TEXT, -- da doi tu phone_number -> phone
  email TEXT,
  party_size INT DEFAULT 1,
  is_attending BOOLEAN,
  wishes TEXT,
  
  guest_group TEXT, -- Phan loai khach
  
  is_synced_to_sheet BOOLEAN DEFAULT false,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bảng JOB_QUEUE
CREATE TABLE IF NOT EXISTS job_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  payload JSONB NOT NULL,
  status TEXT DEFAULT 'PENDING',
  attempts INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ROW LEVEL SECURITY (RLS)

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE weddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE rsvps ENABLE ROW LEVEL SECURITY;

-- Drop policies if exist to avoid errors on re-run
DROP POLICY IF EXISTS "User xem profile của chính mình" ON profiles;
DROP POLICY IF EXISTS "User cập nhật profile của chính mình" ON profiles;
DROP POLICY IF EXISTS "Host xem và sửa đám cưới của mình" ON weddings;
DROP POLICY IF EXISTS "Khách vãng lai xem đám cưới đã publish (thông qua Slug)" ON weddings;
DROP POLICY IF EXISTS "Host xem toàn bộ RSVP của đám cưới mình" ON rsvps;
DROP POLICY IF EXISTS "Khách mời được phép tạo RSVP mới" ON rsvps;

-- Policy cho PROFILES:
CREATE POLICY "User xem profile của chính mình" ON profiles
  FOR SELECT USING (auth.uid() = id);
CREATE POLICY "User cập nhật profile của chính mình" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Policy cho WEDDINGS:
CREATE POLICY "Host xem và sửa đám cưới của mình" ON weddings
  FOR ALL USING (auth.uid() = host_id);
  
CREATE POLICY "Khách vãng lai xem đám cưới đã publish (thông qua Slug)" ON weddings
  FOR SELECT USING (deployment_status = 'published');

-- Policy cho RSVPS:
CREATE POLICY "Host xem toàn bộ RSVP của đám cưới mình" ON rsvps
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM weddings WHERE id = rsvps.wedding_id AND host_id = auth.uid())
  );

CREATE POLICY "Khách mời được phép tạo RSVP mới" ON rsvps
  FOR INSERT WITH CHECK (true); 

-- 5. TRIGGER & FUNCTIONS

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_weddings_updated_at ON weddings;
CREATE TRIGGER update_weddings_updated_at BEFORE UPDATE ON weddings
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Function: Auto-create Profile on Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. SEED DATA (Dữ liệu mẫu)
-- Insert sample templates
INSERT INTO templates (code, name, thumbnail_url, repo_branch, default_content)
VALUES 
('vintage-rose', 'Vintage Rose', '/templates/vintage-rose.jpg', 'theme-vintage', '{"primary_color": "#e11d48", "font_family": "Playfair Display"}'::jsonb),
('modern-minimal', 'Modern Minimal', '/templates/modern-minimal.jpg', 'theme-minimal', '{"primary_color": "#1f2937", "font_family": "Inter"}'::jsonb),
('luxury-gold', 'Luxury Gold', '/templates/luxury-gold.jpg', 'theme-luxury', '{"primary_color": "#d97706", "font_family": "Cormorant Garamond"}'::jsonb)
ON CONFLICT (code) DO NOTHING;
