// import Head from 'next/head'
// import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
// import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
// import TodoList from '@/components/TodoList'

// export default function Home() {
//   const session = useSession()
//   const supabase = useSupabaseClient()

//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name='description' content='Generated by create next app' />
//         <meta name='viewport' content='width=device-width, initial-scale=1' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>
//       <div className='w-full h-full bg-200'>
//         {!session ? (
//           <div className='flex items-center justify-center min-w-full min-h-screen'>
//             <div className='flex items-center justify-center w-full h-full p-4'>
//               <div className='flex flex-col w-full h-full max-w-sm p-5 text-base bg-white shadow sm:h-auto sm:w-2/5'>
//                 <span className='pb-2 mx-4 mb-1 font-sans text-4xl text-center border-b align-center'>Login</span>
//                 <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme='dark' />
//               </div>
//             </div>
//           </div>
//         ) : (
//           <div
//             className='flex flex-col items-center justify-center w-full h-full p-4'
//             style={{ minWidth: 250, maxWidth: 600, margin: 'auto' }}
//           >
//             <TodoList session={session} />
//             <button
//               className='w-full mt-12 btn-black'
//               onClick={async () => {
//                 const { error } = await supabase.auth.signOut()
//                 if (error) console.log('Error logging out:', error.message)
//               }}
//             >
//               Logout
//             </button>
//           </div>
//         )}
//       </div>
//     </>
//   )
// }
